// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-t3UP9hy6bF1_le3DGryj_iu0aRekWw',
    appId: '1:593783649623:web:7e7eabac0ed1c44a907a12',
    messagingSenderId: '593783649623',
    projectId: 'expenseflow-tr',
    authDomain: 'expenseflow-tr.firebaseapp.com',
    storageBucket: 'expenseflow-tr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkr288t08voqh46kCoMbiHf8VrIbnzJdg',
    appId: '1:593783649623:android:4fc06a707abc1c3d907a12',
    messagingSenderId: '593783649623',
    projectId: 'expenseflow-tr',
    storageBucket: 'expenseflow-tr.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilt_UroNxvkVoZgZNVrSCF76hkB4krrA',
    appId: '1:593783649623:ios:effbad64cc3e5700907a12',
    messagingSenderId: '593783649623',
    projectId: 'expenseflow-tr',
    storageBucket: 'expenseflow-tr.firebasestorage.app',
    iosBundleId: 'com.expenseflow.trac',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh-t3UP9hy6bF1_le3DGryj_iu0aRekWw',
    appId: '1:593783649623:web:a4fb4aa25a4c4311907a12',
    messagingSenderId: '593783649623',
    projectId: 'expenseflow-tr',
    authDomain: 'expenseflow-tr.firebaseapp.com',
    storageBucket: 'expenseflow-tr.firebasestorage.app',
  );
}
